site_name: StrangeScout Docs
site_description: 'Documentation for the StrangeScout scouting system'
site_url: 'https://the-red-alliance.github.io/strangescout-docs/'
site_author: 'The Red Alliance projects maintainers'

repo_name: 'Deployment Repo'
repo_url: 'https://github.com/the-red-alliance/strangescout-deploy'

# disable editing
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2019 The Red Alliance Project'

# Configuration
theme:
  name: 'material'
  font:
    text: 'Noto Sans'
    code: 'Roboto Mono'
  logo:
    icon: 'book'

nav:
  - Home: index.md
  - Installation Guide: installation-guide.md
  - Scouter Guide: scouter-guide.md
  - Premade Game Templates: premade-templates.md
  - StrangeScout API:
    - Authentication Routes: strangescout-api/authentication-routes.md

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - codehilite:
      linenums: true
  - toc:
      permalink: true